version: '3'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: sh /code/docker-start.sh
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_PASSWORD

volumes:
    postgres_data:
